const itemsGuild = {
  Daigon: [
    { name: "Baston de Daigon", type: "arma principal" },
    { name: "Baston de Daigon", type: "arma secundaria" },
    { name: "Escudo de Daigon", type: "arma principal" },
    { name: "Escudo de Daigon", type: "arma secundaria" },
    { name: "Yelmo de legionario inmortal", type: "casco" },
    { name: "Rostro del vencedor elegido", type: "casco" },
    { name: "Agarre intenso", type: "guantes" },
    { name: "Pantalones de supervisor espectral", type: "pantalones" },
    { name: "Grebas de pretor real", type: "pantalones" },
    { name: "Pantalones de buscador imperial", type: "pantalones" },
    { name: "Pantalones de reposo sagrado", type: "pantalones" },
    { name: "Gorjal draconiano intenso", type: "collar" },
  ],

  Leviathan: [
    { name: "Dagas de Leviatan", type: "arma principal" },
    { name: "Dagas de Leviatan", type: "arma secundaria" },
    { name: "Arco de Leviatan", type: "arma principal" },
    { name: "Arco de Leviatan", type: "arma secundaria" },
    { name: "Halo de primera luz", type: "casco" },
    { name: "Manoplas de supervisor espectral", type: "guantes" },
    { name: "Guantes de pretor real", type: "guantes" },
    { name: "Guantes de buscador imperial", type: "guantes" },
    { name: "Guantes de reposo sagrado", type: "guantes" },
    { name: "Brazalete de la resaca violenta", type: "brazalete" },
    { name: "Banda de sangre ancestral", type: "anillo1" },
    { name: "Banda de sangre ancestral", type: "anillo2" },
  ],

  PakiloNaru: [
    { name: "Mandoble de Naru", type: "arma principal" },
    { name: "Mandoble de Naru", type: "arma secundaria" },
    { name: "Lanza de Naru", type: "arma principal" },
    { name: "Lanza de Naru", type: "arma secundaria" },
    { name: "Tunica de supervisor espectral", type: "pechera" },
    { name: "Armadura de placas de pretor real", type: "pechera" },
    { name: "Tunica de buscador imperial", type: "pechera" },
    { name: "Traje de reposo sagrado", type: "pechera" },
    { name: "Pantalon del vencedor elegido", type: "pantalones" },
    { name: "Grebas de victoria sencilla", type: "pantalones" },
    { name: "Sortija runica de yunquenegro", type: "anillo1" },
    { name: "Sortija runica de yunquenegro", type: "anillo2" },
    { name: "Simbolo del avance de la naturaleza", type: "anillo1" },
    { name: "Simbolo del avance de la naturaleza", type: "anillo2" },
  ],

  ManticusBrothers: [
    { name: "Ballestas de Akman", type: "arma principal" },
    { name: "Ballestas de Akman", type: "arma secundaria" },
    { name: "Varita de Deckman", type: "arma principal" },
    { name: "Varita de Deckman", type: "arma secundaria" },
    { name: "Botas de supervisor espectral", type: "botas" },
    { name: "Escarpes de pretor real", type: "botas" },
    { name: "Botas de buscador imperial", type: "botas" },
    { name: "Calzado de reposo sagrado", type: "botas" },
    { name: "Grebas de legionario inmortal", type: "pantalones" },
    { name: "Pantalones de primera luz", type: "pantalones" },
    { name: "Pantalones de colmillo prisrino", type: "pantalones" },
    { name: "Collar de ritual primitivo", type: "collar" },
  ],

  ArmaArchiBoss: [
    { name: "Mandoble Tevent", type: "archiboss1" },
    { name: "Dagas Tevent", type: "archiboss1" },
    { name: "Arco Tevent", type: "archiboss1" },
    { name: "Varita Tevent", type: "archiboss1" },
    { name: "Escudo Bellandir", type: "archiboss1" },
    { name: "Ballestas Bellandir", type: "archiboss1" },
    { name: "Baculo Bellandir", type: "archiboss1" },
    { name: "Lanza Bellandir", type: "archiboss1" },
    { name: "Escudo Deluzhnoa", type: "archiboss1" },
    { name: "Dagas Deluzhnoa", type: "archiboss1" },
    { name: "Arco Deluzhnoa", type: "archiboss1" },
    { name: "Baculo Deluzhnoa", type: "archiboss1" },
    { name: "Lanza Deluzhnoa", type: "archiboss1" },
    { name: "Mandoble Cordy", type: "archiboss1" },
    { name: "Ballestas Cordy", type: "archiboss1" },
    { name: "Varita Cordy", type: "archiboss1" },
    { name: "Mandoble Tevent", type: "archiboss2" },
    { name: "Dagas Tevent", type: "archiboss2" },
    { name: "Arco Tevent", type: "archiboss2" },
    { name: "Varita Tevent", type: "archiboss2" },
    { name: "Escudo Bellandir", type: "archiboss2" },
    { name: "Ballestas Bellandir", type: "archiboss2" },
    { name: "Baculo Bellandir", type: "archiboss2" },
    { name: "Lanza Bellandir", type: "archiboss2" },
    { name: "Escudo Deluzhnoa", type: "archiboss2" },
    { name: "Dagas Deluzhnoa", type: "archiboss2" },
    { name: "Arco Deluzhnoa", type: "archiboss2" },
    { name: "Baculo Deluzhnoa", type: "archiboss2" },
    { name: "Lanza Deluzhnoa", type: "archiboss2" },
    { name: "Mandoble Cordy", type: "archiboss2" },
    { name: "Ballestas Cordy", type: "archiboss2" },
    { name: "Varita Cordy", type: "archiboss2" },
  ],

  ItemArchiBoss: [
    { name: "Corona infinidad helada", type: "casco" },
    { name: "Circulo reposo sagrado", type: "casco" },
    { name: "Mascara supervisor espectral", type: "casco" },
    { name: "Diadema imperial", type: "casco" },
    { name: "Visera Pretor Real", type: "casco" },
    { name: "Manto alcance gelido", type: "capa" },
    { name: "Broche noble linaje", type: "collar" },
    { name: "Collar ira naturaleza", type: "collar" },
    { name: "Las restricciones guerra glacial", type: "brazalete" },
    { name: "Bobina soberano verde", type: "brazalete" },
    { name: "Brazaletes infernal Demonpact", type: "brazalete" },
    { name: "Sello primera nieve", type: "anillo1" },
    { name: "Sello primera nieve", type: "anillo2" },
    { name: "Sello señor treant", type: "anillo1" },
    { name: "Sello señor treant", type: "anillo2" },
    { name: "Faja fuerza Treant", type: "cinturon" },
  ],
};

export default itemsGuild;
